# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eef2919d261861ff12ea6df199550d6e6b3f5d33a674454dee9c89b4aaac8d37ac130878316bcb204866c34c4426e52aa009e835fee5044e5bc349cf77056ba3

test:
  secret_key_base: 4be4af6e4d3ad840dfd99df31539cdfae2b1fa311efa35e3341e75bfee872387ef504d593e886ff65a28c757dbb86bb097743bfaf1e6c1ead3833b57da0c9f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
